version: "3"
services:
  notifications:
    image: incs/notifications
    ports:
      - "8006:8006"
    environment:
      - PRODUCTION=true
      - DEBUG=false
      - AWS_EMAIL_API_KEY=AKIAIMT6FSAPFC26ONAQ
      - AWS_EMAIL_API_SECRET=AqZ9a2W5uI7ccHuJE8f8HZEUBWBX3TxYifu3kZRghDLk
      - AWS_EMAIL_REGION=eu-west-1
      - EMAIL_SENDER=grigore@instacarshare.com
      - TWILIO_ACCOUNT_SID=AC10593464d6d0694b5af90a531bd9179f
      - TWILIO_TOKEN=aef6313cd48a0ecf01be1e367c6b348f
      - SMS_SENDER=+14152002778
    logging:
      driver: "json-file"
    command: gunicorn -c app/src/configs/gunicorn_conf.py app.src.wsgi.wsgi:app

