version: "3"
services:
  notificationserver:
    image: incs/notificationserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
      - "8002:8002"
    command: bash -c "python src/wsServer.py"

