version: "2"
services:
  notificationserver:
    image: incs/notificationserver
    ports:
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./:/app/
    command: bash -c "python src/wsServer.py"

