version: "2"
services:
  notifications:
    image: incs/notifications
    ports:
      - "8001:8001"
      - "8002:8002"
    environment:
      - PRODUCTION=false
      - DEBUG=true
      - AWS_EMAIL_API_KEY=AKIAIMT6FSAPFC26ONAQ
      - AWS_EMAIL_API_SECRET=AqZ9a2W5uI7ccHuJE8f8HZEUBWBX3TxYifu3kZRghDLk
      - AWS_EMAIL_REGION=eu-west-1
      - EMAIL_SENDER=grigore@instacarshare.com
    volumes:
      - ./:/app/
    command: bash -c "python src/wsServer.py"
