INVALID_JSON = "INVALID_JSON"
HANDLER_CRASHED = "HANDLER_CRASHED"
NO_FILE_SPECIFIED = 'NO_FILE_SPECIFIED'
UNKNOWN_FILE = 'UNKNOWN_FILE'
MISSING_BUCKET_NAME = 'MISSING_BUCKET_NAME'
MISSING_BUCKET_REGION = 'MISSING_BUCKET_REGION'
